TST: stop using mixed bool/int + strings as input to np.asarray
In NumPy 1.21.0 this will start giving a FutureWarning, which fails the
tests in development mode. Here is a representative example plus the
full set of test failures that this fixes:

```
scipy/stats/tests/test_contingency.py:209: in test_bad_association_args
    assert_raises(ValueError, association, [[1, 2], ["dd", 4]], 'cramer')
scipy/stats/contingency.py:375: in association
    arr = np.asarray(observed)
E   FutureWarning: Promotion of numbers and bools to strings is deprecated. In the future, code such as `np.concatenate((['string'], [0]))` will raise an error, while `np.asarray(['string', 0])` will return an array with `dtype=object`.  To avoid the warning while retaining a string result use `dtype='U'` (or 'S').  To get an array of Python objects use `dtype=object`. (Warning added in NumPy 1.21)
        correction = False
        lambda_    = None
        method     = 'cramer'
        observed   = [[1, 2], ['dd', 4]]
=========================== short test summary info ============================
FAILED scipy/cluster/tests/test_disjoint_set.py::test_init - FutureWarning: P...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_len - FutureWarning: Pr...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_contains[10] - FutureWa...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_contains[100] - FutureW...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_add[10] - FutureWarning...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_add[100] - FutureWarnin...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_element_not_present - F...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_linear_union_sequence[10-forwards]
FAILED scipy/cluster/tests/test_disjoint_set.py::test_linear_union_sequence[10-backwards]
FAILED scipy/cluster/tests/test_disjoint_set.py::test_linear_union_sequence[100-forwards]
FAILED scipy/cluster/tests/test_disjoint_set.py::test_linear_union_sequence[100-backwards]
FAILED scipy/cluster/tests/test_disjoint_set.py::test_self_unions[10] - Futur...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_self_unions[100] - Futu...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_equal_size_ordering[10-ab]
FAILED scipy/cluster/tests/test_disjoint_set.py::test_equal_size_ordering[10-ba]
FAILED scipy/cluster/tests/test_disjoint_set.py::test_equal_size_ordering[100-ab]
FAILED scipy/cluster/tests/test_disjoint_set.py::test_equal_size_ordering[100-ba]
FAILED scipy/cluster/tests/test_disjoint_set.py::test_binary_tree[5] - Future...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_binary_tree[10] - Futur...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_subsets[10] - FutureWar...
FAILED scipy/cluster/tests/test_disjoint_set.py::test_subsets[100] - FutureWa...
FAILED scipy/stats/tests/test_contingency.py::test_bad_association_args - Fut...
```