BUG: Docstring claims to accept array_like for T, but does not
Tries to call T.shape, but this produces

"AttributeError: 'list' object has no attribute 'shape'" etc.

change so that it explicitly converts to array